name: dlox
description: A sample command-line application.

environment:
  sdk: '>=2.15.0-0 <3.0.0'

dependencies:
  # TODO remove sprintf
  sprintf: ^6.0.0

dev_dependencies:
  extra_pedantic: ^2.0.0
  test:
